---
version: '2.0'
services:
  nftdocker:
    image: 'zjuuu/wizardapi:1.0'
    expose:
      - port: 8080
        as: 80
        accept:
          - yourdomain.com
        to:
          - global: true
    env:
      - DATABASE_URL=url
      - API_KEY=apikey
profiles:
  compute:
    nftdocker:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      attributes:
          host: akash
      signedBy:
          anyOf:
            - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
            - "akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4"  
      pricing:
        nftdocker:
          denom: uakt
          amount: 1000
deployment:
  nftdocker:
    dcloud:
      profile: nftdocker
      count: 1